# Generated by Django 4.2.7 on 2025-09-19 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("government", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="roadsegment",
            name="contractor_email",
            field=models.EmailField(
                default="", help_text="Contractor's email address", max_length=254
            ),
        ),
        migrations.AddField(
            model_name="roadsegment",
            name="contractor_id",
            field=models.CharField(
                default="",
                help_text="Unique contractor identification number",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="roadsegment",
            name="contractor_phone",
            field=models.CharField(
                default="", help_text="Contractor's phone number", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="roadsegment",
            name="money_sanctioned",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Amount sanctioned for the project",
                max_digits=12,
            ),
        ),
    ]
