# Generated by Django 5.2.4 on 2025-07-05 08:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pothole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=7, help_text='Latitude coordinate of the pothole location', max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, help_text='Longitude coordinate of the pothole location', max_digits=10)),
                ('num_potholes', models.PositiveIntegerField(default=1, help_text='Number of potholes at this location')),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('verified', 'Verified'), ('in_progress', 'In Progress'), ('fixed', 'Fixed'), ('closed', 'Closed')], default='reported', help_text='Current status of the pothole report', max_length=20)),
                ('image', models.ImageField(blank=True, help_text='Image of the pothole', null=True, upload_to='pothole_images/')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='When the pothole was reported')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, help_text='Additional description of the pothole', null=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', help_text='Severity level of the pothole', max_length=10)),
            ],
            options={
                'verbose_name': 'Pothole Report',
                'verbose_name_plural': 'Pothole Reports',
                'ordering': ['-timestamp'],
            },
        ),
    ]
