# Generated by Django 5.2.4 on 2025-07-25 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potholes', '0002_pothole_frame_image_base64_pothole_frame_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='pothole',
            name='contractor',
            field=models.CharField(blank=True, help_text='Contractor responsible for the road', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pothole',
            name='road_c_date',
            field=models.DateField(blank=True, help_text='Road completion date', null=True),
        ),
    ]
