# Generated by Django 5.2.4 on 2025-08-31 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potholes', '0003_pothole_contractor_pothole_road_c_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pothole',
            name='frame_image',
            field=models.ImageField(blank=True, help_text='Frame image file', null=True, upload_to='pothole_frames/'),
        ),
        migrations.AlterField(
            model_name='pothole',
            name='frame_image_base64',
            field=models.TextField(blank=True, help_text='Base64 encoded image data from CSV frame (deprecated)', null=True),
        ),
    ]
