# Generated by Django 4.2.7 on 2025-10-06 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("potholes", "0004_pothole_frame_image_alter_pothole_frame_image_base64"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoadHealth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "points",
                    models.JSONField(
                        help_text="Array of [lat, lng] coordinates for the road segment"
                    ),
                ),
                ("pothole_count", models.PositiveIntegerField(default=0)),
                ("is_under_warranty", models.BooleanField(default=False)),
                (
                    "health_status",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("warning", "Warning"),
                            ("caution", "Caution"),
                            ("good", "Good"),
                        ],
                        default="good",
                        max_length=20,
                    ),
                ),
                (
                    "contractor_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "contractor_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "contractor_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "contractor_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Road Health Data",
                "verbose_name_plural": "Road Health Data",
                "ordering": ["-last_updated"],
            },
        ),
        migrations.CreateModel(
            name="MessageSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_auto_message_sent", models.DateTimeField(blank=True, null=True)),
                ("next_auto_message_due", models.DateTimeField(blank=True, null=True)),
                ("auto_message_enabled", models.BooleanField(default=True)),
                ("message_frequency_days", models.PositiveIntegerField(default=5)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "road_health",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_schedule",
                        to="potholes.roadhealth",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message Schedule",
                "verbose_name_plural": "Message Schedules",
            },
        ),
        migrations.CreateModel(
            name="ContractorMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contractor_email", models.EmailField(max_length=254)),
                ("contractor_phone", models.CharField(max_length=20)),
                ("message", models.TextField()),
                (
                    "message_type",
                    models.CharField(
                        choices=[("auto", "Automatic"), ("manual", "Manual")],
                        default="manual",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "road_health",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="potholes.roadhealth",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contractor Message",
                "verbose_name_plural": "Contractor Messages",
                "ordering": ["-created_at"],
            },
        ),
    ]
